"""Executor module that writes config files and calls uv commands.

Phase 4 of the pipeline: creates the target directory, writes
pyproject.toml and .gitignore, then runs ``uv sync`` and ``uv add``
as subprocess calls with streamed output.
"""

import os
import shutil
import subprocess
import sys

from rich.console import Console

console = Console()

# Minimal .gitignore for Python + data-science workspaces
_GITIGNORE = """\
# Python
__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
*.egg

# Virtual environments
.venv/
venv/
ENV/

# Jupyter
.ipynb_checkpoints/

# Environment
.env

# IDE
.idea/
.vscode/
*.swp
*.swo

# Verification script (generated by create-uv-ml, not meant for git)
verify_env.py

# OS
.DS_Store
Thumbs.db
"""

# Verification script dropped into the target directory
_VERIFY_ENV_SCRIPT = '''\
#!/usr/bin/env python3
"""Environment verification script.

Run this after activating your environment to verify that CUDA, Python,
PyTorch, and all selected packages are working correctly.

Usage:
    source .venv/bin/activate
    python verify_env.py
"""

from __future__ import annotations

import importlib
import platform
import subprocess
import sys


def _print_header(text: str) -> None:
    print(f"\\n{'=' * 50}")
    print(f"  {text}")
    print(f"{'=' * 50}")


def _print_ok(msg: str) -> None:
    print(f"  [OK] {msg}")


def _print_warn(msg: str) -> None:
    print(f"  [WARN] {msg}")


def _print_fail(msg: str) -> None:
    print(f"  [FAIL] {msg}")


def check_python() -> None:
    """Verify Python version."""
    _print_header("Python")
    version = platform.python_version()
    _print_ok(f"Python {version}")
    _print_ok(f"Executable: {sys.executable}")


def check_cuda() -> None:
    """Verify NVIDIA CUDA/driver availability."""
    _print_header("NVIDIA CUDA / Driver")
    try:
        result = subprocess.run(
            ["nvidia-smi"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            lines = result.stdout.strip().split("\\n")[:4]
            for line in lines:
                print(f"  {line}")
            _print_ok("nvidia-smi is accessible")
        else:
            _print_fail("nvidia-smi returned an error")
    except FileNotFoundError:
        _print_warn("nvidia-smi not found — no NVIDIA GPU or driver not installed")
    except subprocess.TimeoutExpired:
        _print_fail("nvidia-smi timed out")


def check_torch() -> None:
    """Verify PyTorch installation and GPU access."""
    _print_header("PyTorch")
    try:
        import torch

        _print_ok(f"torch {torch.__version__}")

        if torch.cuda.is_available():
            _print_ok("CUDA is available")
            _print_ok(f"CUDA version: {torch.version.cuda}")
            _print_ok(f"cuDNN version: {torch.backends.cudnn.version()}")
            device_count = torch.cuda.device_count()
            _print_ok(f"GPU count: {device_count}")
            for i in range(device_count):
                name = torch.cuda.get_device_name(i)
                _print_ok(f"  GPU {i}: {name}")
            x = torch.rand(3, 3).cuda()
            y = x @ x.T
            _print_ok(f"GPU tensor test passed ({y.device})")
        else:
            _print_warn("CUDA not available — running on CPU")
            x = torch.rand(3, 3)
            y = x @ x.T
            _print_ok("CPU tensor test passed")

    except ImportError:
        _print_fail("torch is not installed")


def check_torchvision() -> None:
    """Verify torchvision."""
    try:
        import torchvision

        _print_ok(f"torchvision {torchvision.__version__}")
    except ImportError:
        _print_warn("torchvision is not installed")


def _try_import(module_name: str, display_name: str | None = None) -> bool:
    """Try importing a module and print the result."""
    name = display_name or module_name
    try:
        mod = importlib.import_module(module_name)
        version = getattr(mod, "__version__", "unknown")
        _print_ok(f"{name} {version}")
        return True
    except ImportError:
        _print_warn(f"{name} is not installed")
        return False


def check_extra_packages() -> None:
    """Verify optional packages."""
    _print_header("Extra Packages")

    _try_import("torchaudio", "torchaudio")
    _try_import("transformers", "transformers")
    _try_import("datasets", "datasets")
    _try_import("accelerate", "accelerate")
    _try_import("tensorboard", "tensorboard")
    _try_import("numpy", "numpy")
    _try_import("pandas", "pandas")
    _try_import("matplotlib", "matplotlib")
    _try_import("sklearn", "scikit-learn")
    _try_import("scipy", "scipy")
    _try_import("jupyterlab", "jupyterlab")
    _try_import("cv2", "opencv-python")
    _try_import("PIL", "Pillow")
    _try_import("tqdm", "tqdm")
    _try_import("rich", "rich")
    _try_import("requests", "requests")
    _try_import("pydantic", "pydantic")


def main() -> None:
    print("🔍 Environment Verification")
    print("This script checks your Python environment setup.")

    check_python()
    check_cuda()
    check_torch()
    check_torchvision()
    check_extra_packages()

    _print_header("Summary")
    print("  If you see [OK] for the packages you need, you\\'re ready to go!")
    print("  [WARN] means the package is optional or not installed.")
    print("  [FAIL] means something is broken and needs fixing.")
    print()


if __name__ == "__main__":
    main()
'''


def check_uv_available() -> None:
    """Check that uv is installed and available in PATH."""
    if shutil.which("uv") is None:
        console.print("[bold red]Error: 'uv' is not installed or not in PATH.[/bold red]")
        console.print("Install it with: curl -LsSf https://astral.sh/uv/install.sh | sh")
        sys.exit(1)


def write_pyproject(target_dir: str, content: str) -> None:
    """Write pyproject.toml to the target directory."""
    os.makedirs(target_dir, exist_ok=True)
    path = os.path.join(target_dir, "pyproject.toml")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    console.print(f"[green]  ✓ Wrote {path}[/green]")


def write_gitignore(target_dir: str) -> None:
    """Write a .gitignore to the target directory."""
    path = os.path.join(target_dir, ".gitignore")
    with open(path, "w", encoding="utf-8") as f:
        f.write(_GITIGNORE)
    console.print(f"[green]  ✓ Wrote {path}[/green]")


def write_verify_env(target_dir: str) -> None:
    """Write the verification script to the target directory."""
    path = os.path.join(target_dir, "verify_env.py")
    with open(path, "w", encoding="utf-8") as f:
        f.write(_VERIFY_ENV_SCRIPT)
    console.print(f"[green]  ✓ Wrote {path}[/green]")


def uv_sync(target_dir: str, python_version: str) -> None:
    """Run ``uv sync --python <version>`` in the target directory.

    This creates the .venv, downloads the requested Python interpreter
    (if necessary), and installs the core dependencies declared in
    pyproject.toml.
    """
    console.print("[yellow]📦 Running uv sync to install core dependencies...[/yellow]")
    console.print(
        "[dim]   (PyTorch CUDA wheels are ~2 GB, this may take 10-30 minutes "
        "depending on your network)[/dim]"
    )
    try:
        process = subprocess.Popen(
            ["uv", "sync", "--python", python_version],
            cwd=target_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        if process.stdout is not None:
            for line in process.stdout:
                console.print(f"[dim]{line.rstrip()}[/dim]")
        retcode = process.wait()
        if retcode != 0:
            raise subprocess.CalledProcessError(retcode, "uv sync")
        console.print("[green]  ✓ uv sync completed[/green]")
    except subprocess.CalledProcessError:
        console.print("[bold red]✗ uv sync failed[/bold red]")
        sys.exit(1)


def uv_add(target_dir: str, packages: list[str]) -> None:
    """Run ``uv add <packages>`` in the target directory.

    Called after ``uv sync`` so that uv's resolver can solve the extra
    packages against the already-locked base dependencies.
    """
    if not packages:
        return

    console.print(f"[yellow]📦 Installing additional packages: {', '.join(packages)}[/yellow]")
    try:
        process = subprocess.Popen(
            ["uv", "add", *packages],
            cwd=target_dir,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        if process.stdout is not None:
            for line in process.stdout:
                console.print(f"[dim]{line.rstrip()}[/dim]")
        retcode = process.wait()
        if retcode != 0:
            raise subprocess.CalledProcessError(retcode, "uv add")
        console.print("[green]  ✓ Additional packages installed[/green]")
    except subprocess.CalledProcessError:
        console.print("[bold red]✗ uv add failed[/bold red]")
        sys.exit(1)
