"""Runner module that creates the project directory, writes config, and calls uv commands."""

import os
import subprocess
import sys

from rich.console import Console

console = Console()


def create_project(project_name: str, pyproject_content: str) -> None:
    """Create the project folder and initialize the uv environment."""

    if os.path.exists(project_name):
        console.print(f"[bold red]Error: Directory {project_name} already exists![/bold red]")
        sys.exit(1)

    console.print(f"[yellow]📁 Creating project directory: {project_name}[/yellow]")
    os.makedirs(project_name, exist_ok=True)

    # Write pyproject.toml
    pyproject_path = os.path.join(project_name, "pyproject.toml")
    with open(pyproject_path, "w", encoding="utf-8") as f:
        f.write(pyproject_content)
    console.print(f"[green]  ✓ Wrote {pyproject_path}[/green]")

    # Run uv sync to install dependencies
    console.print("[yellow]📦 Running uv sync to install dependencies (this may take a few minutes)...[/yellow]")
    try:
        result = subprocess.run(
            ["uv", "sync"],
            cwd=project_name,
            capture_output=True,
            text=True,
            check=True,
        )
        console.print(result.stdout)
        console.print("[green]  ✓ uv sync completed[/green]")
    except subprocess.CalledProcessError as e:
        console.print(f"[bold red]✗ uv sync failed:[/bold red]")
        console.print(e.stdout)
        console.print(e.stderr)
        sys.exit(1)

    # Create README.md (if uv init didn't generate one)
    readme_path = os.path.join(project_name, "README.md")
    if not os.path.exists(readme_path):
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(f"# {project_name}\n\nGenerated by create-uv-ml.\n")
        console.print(f"[green]  ✓ Wrote {readme_path}[/green]")
