"""Template module for generating project scaffold files."""

from create_uv_ml.generator import Framework


def generate_gitignore() -> str:
    """Generate a .gitignore for Python + data science projects."""
    return """\
# Python
__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
*.egg

# Virtual environments
.venv/
venv/
ENV/

# Data science
data/
*.csv
*.tsv
!example_data/*.csv

# Model artifacts
*.pt
*.pth
*.ckpt
*.h5
*.pb
*.onnx

# Jupyter
.ipynb_checkpoints/

# Environment
.env

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""


def generate_readme(project_name: str, framework: Framework, cuda: str | None) -> str:
    """Generate a project README.md."""
    config = f"{framework}"
    if cuda:
        config += f" + {cuda}"

    return f"""\
# {project_name}

Generated by [create-uv-ml](https://github.com/slowcage/create-uv-ml).

**Configuration:** {config}

## Setup

```bash
cd {project_name}
uv sync
```

## Usage

```bash
source .venv/bin/activate
```

## Project Structure

```text
{project_name}/
├── pyproject.toml
├── uv.lock
├── README.md
├── data/                   # Place your datasets here
└── src/
    └── {project_name}/
        ├── __init__.py
        └── train.py        # Training entry point
```
"""


def generate_train_py_pytorch(project_name: str) -> str:
    """Generate a PyTorch training template."""
    return f'''\
"""Training script for {project_name}."""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {{device}}")


# --- Model ---
class SimpleModel(nn.Module):
    def __init__(self, input_dim: int = 64, hidden_dim: int = 128, output_dim: int = 10):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# --- Data ---
def create_dummy_dataloader(batch_size: int = 32) -> DataLoader:
    x = torch.randn(1000, 64)
    y = torch.randint(0, 10, (1000,))
    dataset = TensorDataset(x, y)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)


# --- Training ---
def train(epochs: int = 10, lr: float = 1e-3) -> None:
    model = SimpleModel().to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    dataloader = create_dummy_dataloader()

    for epoch in range(epochs):
        total_loss = 0.0
        correct = 0
        total = 0
        for batch_x, batch_y in dataloader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            correct += (outputs.argmax(dim=1) == batch_y).sum().item()
            total += batch_y.size(0)

        avg_loss = total_loss / len(dataloader)
        accuracy = correct / total
        print(f"Epoch {{epoch + 1}}/{{epochs}} - Loss: {{avg_loss:.4f}} - Acc: {{accuracy:.4f}}")


if __name__ == "__main__":
    train()
'''


def generate_train_py_tensorflow(project_name: str) -> str:
    """Generate a TensorFlow training template."""
    return f'''\
"""Training script for {project_name}."""

import tensorflow as tf


# --- Data ---
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0


# --- Model ---
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation="relu", input_shape=(784,)),
    tf.keras.layers.Dense(10, activation="softmax"),
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)


# --- Training ---
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.1)
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {{test_acc:.4f}}")
'''


def generate_analysis_py(project_name: str) -> str:
    """Generate a scientific computing analysis template."""
    return f'''\
"""Analysis script for {project_name}."""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# --- Data ---
np.random.seed(42)
n_samples = 1000
x = np.random.randn(n_samples, 4)
y = (x[:, 0] + x[:, 1] > 0).astype(int)

df = pd.DataFrame(x, columns=["feature_1", "feature_2", "feature_3", "feature_4"])
df["target"] = y
print(df.head())
print(df.describe())


# --- Visualization ---
plt.figure(figsize=(8, 5))
plt.scatter(df["feature_1"], df["feature_2"], c=df["target"], cmap="coolwarm", alpha=0.6)
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Feature Distribution")
plt.savefig("scatter.png", dpi=150)
plt.close()
print("Saved scatter.png")


# --- Model ---
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
clf = LogisticRegression()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
print(f"Accuracy: {{accuracy_score(y_test, y_pred):.4f}}")
'''


def generate_init_py(project_name: str) -> str:
    """Generate __init__.py for the project package."""
    return f'"""{project_name}."""\n'


def generate_train_py(project_name: str, framework: Framework) -> str:
    """Generate the appropriate training/analysis script based on framework."""
    if framework == "PyTorch":
        return generate_train_py_pytorch(project_name)
    elif framework == "TensorFlow":
        return generate_train_py_tensorflow(project_name)
    else:
        return generate_analysis_py(project_name)
